baseURL = 'https://docscontent.pages.dev/'
languageCode = 'en-us'
title = 'DocsContent'
theme = 'ananke'  # or whichever theme you choose

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allows HTML in markdown
