title: DocsContent
description: Microsoft related content portfolio
#theme: jekyll-theme-tactile
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
nav_enabled: false
plugins:
  - jekyll-remote-theme

nav_external_links:
  - title: Just the Docs on GitHub
    url: https://github.com/just-the-docs/just-the-docs
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false